### ISSUE TITLE
How to save the edited LLM directly?

### ISSUE THREAD

**Issue by Yzk1114** [ChenmienTan/malmen#1]
It seems that the code can only save the editing hyper-network. How can I save the edited language model? I want to use the saved language model directly after editing. Is this possible?

**Comment by ChenmienTan** [comment]
We do not save all edited language models as it is too spatially expensive. The model is edited by the function `edit_model` (line 64 of `editor/base.py`) on the line 124 of `editor/base.py`. You can save the checkpoint there. Feel free to let me know if you have further issue.

**Comment by ChenmienTan** [comment]
> It seems that the code can only save the editing hyper-network. How can I save the edited language model? I want to use the saved language model directly after editing. Is this possible?

We do not save all edited language models as it is too spatially expensive. The model is edited by the function `edit_model` (line 64 of `editor/base.py`) on the line 124 of `editor/base.py`. You can save the checkpoint there. Feel free to let me know if you have further issue.

**Comment by Yzk1114** [comment]
> > It seems that the code can only save the editing hyper-network. How can I save the edited language model? I want to use the saved language model directly after editing. Is this possible?
> 
> We do not save all edited language models as it is too spatially expensive. The model is edited by the function `edit_model` (line 64 of `editor/base.py`) on the line 124 of `editor/base.py`. You can save the checkpoint there. Feel free to let me know if you have further issue.

You mean if I save the language model on the line 124 of `editor/base.py` at last loop, I can get a edited language model with all edits? Thanks for your reply!
