### ISSUE TITLE
关于和MEMIT进行对比的一些疑问

### ISSUE THREAD

**Issue by xpq-tech** [ChenmienTan/malmen#2]
作者您好！MALMEN是一个很优秀的工作！

我注意到您的实验将zsre划分为了测试集和验证集，但MEMIT的实验并未进行该项设置。您在论文中第六页写道“We also use the correct answers to the edit and equivalent prompts to edit GPT-2, T5-XL and GPT-J. Notice that this setting is identical to Meng et al. (2022, 2023) but different with De Cao et al. (2021);”，我对这段话理解为在和MEMIT进行对比的时候（图7的结果），MALMEN并未将zsre划分未测试集和验证集，训练和验证的时候用的是同一个数据集。不知道我的理解是否正确，期待作者反馈。

祝好。

**Comment by ChenmienTan** [comment]
我们将zsRE划分为了训练集和测试集（而非测试集和验证集），因为MALMEN中包含一个需要被训练的超网络。为了公平起见，我们在zsRE的测试集上评估MEMIT，和MALMEN比较。你所引用的句子意思是我们没有事先使用zsRE微调语言模型，再使用反事实进行编辑（MEND的设定），而是对预训练语言模型进行正事实编辑（MEMIT的设定）。

**Comment by xpq-tech** [comment]
感谢您的回复
